In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,65,Female,T-shirt,Clothing,77,New York,S,Cream,Spring,3.7,Yes,Two-Day Shipping,No,Yes,1,Credit Card,Weekly
1,2,53,Male,Sneakers,Footwear,122,New York,L,Teal,Fall,4.2,Yes,Express,No,No,17,Debit Card,Weekly
2,3,23,Female,Belt,Accessories,39,Georgia,M,Teal,Fall,4.2,No,Two-Day Shipping,Yes,No,5,Google Pay,Bi-Weekly
3,4,63,Male,Scarf,Accessories,26,Nevada,S,Olive,Spring,4.4,Yes,Next Day Air,No,No,40,Bank Transfer,Bi-Weekly
4,5,40,Male,Oxfords,Footwear,83,Oregon,XXL,Orange,Spring,3.4,Yes,Two-Day Shipping,Yes,Yes,29,Apple Pay,Bi-Weekly

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3875 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3875.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,31,4,NaN,15,6,12,4,NaN,2,6,2,2,NaN,7,6
top,NaN,NaN,Female,Parka,Outerwear,NaN,Texas,M,Beige,Fall,NaN,No,Standard,No,Yes,NaN,Credit Card,Bi-Weekly
freq,NaN,NaN,1999,228,1028,NaN,315,694,348,1008,NaN,1954,681,1950,1977,NaN,571,671
mean,1950.500000,44.004359,NaN,NaN,NaN,81.903590,NaN,NaN,NaN,NaN,2.994039,NaN,NaN,NaN,NaN,29.943077,NaN,NaN
std,1125.977353,15.161902,NaN,NaN,NaN,39.391889,NaN,NaN,NaN,NaN,1.150936,NaN,NaN,NaN,NaN,17.713410,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,15.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,48.750000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,15.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,82.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,30.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,116.000000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,45.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,150.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,60.000000,NaN,NaN

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             25
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [8]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [9]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [10]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [12]:
#feature engineering
# creating a column age_group
labels = ['Young','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'], q=4 , labels = labels)

In [13]:
df[['age','age_group']].head(12)

    age    age_group
0    65       Senior
1    53  Middle-aged
2    23        Young
3    63       Senior
4    40        Adult
5    67       Senior
6    34        Adult
7    66       Senior
8    66       Senior
9    41        Adult
10   64       Senior
11   43        Adult

In [14]:
#creating column purchase_frequency_days
frequency_mapping = {
    'Daily': 1 ,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly':90 ,
    'Bi-Weekly':14 ,
    'Anually' : 365 
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping).astype('Int64')

In [15]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                        7                 Weekly
1                        7                 Weekly
2                       14              Bi-Weekly
3                       14              Bi-Weekly
4                       14              Bi-Weekly
5                       30                Monthly
6                       90              Quarterly
7                        1                  Daily
8                       14              Bi-Weekly
9                       90              Quarterly

In [16]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0               No             Yes
1               No              No
2              Yes              No
3               No              No
4              Yes             Yes
5               No             Yes
6               No              No
7               No              No
8              Yes             Yes
9               No             Yes

In [17]:
(df['discount_applied'] == df['promo_code_used']).all()# checking  whether discount applied and promo code are same+

np.False_

In [18]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.4.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\yashw\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.13.1)
Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 3.8 MB/s eta 0:00:01
   --------------- ------------------------ 1.0/2.7 MB 3.7 MB/s eta 0:00:01
   --------------------------- ------------ 1.8/2.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 3.8 MB/s  0:00:00
Downloading sqlalchemy-2.0.49-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ------------------- -------------------- 1.0/2.1 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 4.9 MB/s  0:00:00
Downloading greenlet-3.4.0-cp313-cp313-win_amd64.whl (238 kB)
Installing collected packages: psycopg2-binary, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [psycopg2-binary]
   ---------------------------------------- 0/3 [psycopg2-binary]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.4.0 psycopg2-binary-2.9.11 sqlalchemy-2.0.49
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
pip install python-dotenv

Collecting python-dotenv
  Downloading python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.2.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
pip install pymysql

Collecting pymysql
  Using cached pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Using cached pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

load_dotenv(".env", override=True)

engine = create_engine(
    f"mysql+pymysql://{os.getenv('DB_USERNAME')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

with engine.connect() as conn:
    print("Connection successful!")

df.to_sql("customer", engine, if_exists="replace", index=False)

print("Data loaded successfully!")

OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'customer_behavior'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [23]:
import os
print(os.path.exists(".env"))  # Should print True

True